name: Trigger-All-Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"

permissions:
  contents: read
  actions: read

jobs:
    IPQ60XX-LibWrt:
      uses: ./.github/workflows/IPQ60XX-LibWrt.yml
      permissions:
        contents: write
        actions: write
